const Amorph = require('amorph')
const amorphHexPlugin = require('amorph-hex')
const amorphBase58Plugin = require('amorph-base58')
const amorphBufferPlugin = require('amorph-buffer')
const crypto = require('crypto')
const log = require('./log')
const clearTerminal = require('./clearTerminal')

Amorph.loadPlugin(amorphHexPlugin)
Amorph.loadPlugin(amorphBase58Plugin)
Amorph.loadPlugin(amorphBufferPlugin)
Amorph.ready()

log.yellow("Amorph.crossConverter.forms:")
log.green(JSON.stringify(Amorph.crossConverter.forms))

const myAmorph = new Amorph(crypto.randomBytes(120), 'buffer')

log.yellow("ascii:")
log.green(myAmorph.to('ascii'))
log.yellow("utf8:")
log.green(myAmorph.to('utf8'))
log.yellow("base58:")
log.green(myAmorph.to('base58'))
log.yellow("hex:")
log.green(myAmorph.to('hex'))
log.yellow("hex.prefixed:")
log.green(myAmorph.to('hex.prefixed'))
log.yellow("base64:")
log.green(myAmorph.to('base64'))
